version: '3'
services:
  redis:
    image: redis
    command: redis-server --requirepass SoundSync! --bind 0.0.0.0
    container_name: SoundSync-redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    restart: always